# Generated by Django 4.0.5 on 2022-06-30 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Id', models.IntegerField()),
                ('Category_name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.IntegerField()),
                ('Product_name', models.CharField(max_length=2000)),
                ('Quantity', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.category')),
            ],
        ),
    ]
