# Generated by Django 4.0.5 on 2022-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_products_product_id_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_desc',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
