# Generated by Django 4.0.5 on 2022-06-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_products_product_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category_Id',
        ),
    ]
