# Generated by Django 4.0.5 on 2022-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=455),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='', max_length=455),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
