# Generated by Django 4.0.5 on 2022-06-30 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_email', models.EmailField(max_length=254)),
                ('Product_quantity', models.CharField(max_length=1555)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.products')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
