# Generated by Django 4.0.5 on 2022-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='User_email',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
