# Generated by Django 4.0.5 on 2022-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_orderdetails_deliverystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Total_amount',
            field=models.FloatField(default=0),
        ),
    ]
